---
title: "Homework Cars -Haley Mincin"
author: "Haley Mincin"
date: "September 28, 2016"
output: pdf_document
---

Number of rows and columns (in that sequence)

```{r}
dim(iris)
```

Number of rows
```{r}
nrow(iris)
```

Number of columns
```{r}
ncol(iris)
```

Names of variables
```{r}
names(iris) # colnames(iris) also gives that information
```

First 6 rows 
```{r}
head(iris)
```

First 2 rows
```{r}
head(iris,2) # alternately, can use iris[1:2,]
```

Last 6 rows
```{r}
tail(iris) # Number of rows can be controlled, see earlier example involving the head command
```

First row
```{r}
iris[1,]
```
First row, first column
```{r}
iris[1,1]
```

Name of third column
```{r}
names(iris)[3]
```

3 entries from third column
```{r}
head(iris[3],3) # alternately, can use iris[1:3,3]
```
Structure of the dataframe (dataset)
```{r}
str(iris)
```
Summary of the dataframe
```{r}
summary(iris) # for factor/categorical variables, this gives a count of all categories
```
Create a dataframe
```{r}
Person=c("A","B","C","D","E")
Age=c(15,20,25,30,35)
page=data.frame(Person,Age)
mean(Age) # gives the mean of the variable Age, prior to the creation of the dataset
Age="" # (resetting that)
mean(Age) # Haha
mean(page$Age)
mean(page[,2])
summary(page)
```








